# default configuration file
---
update_vocabularies: True
update_pythesint: True
providers:
  ceda:
    type: 'ceda'
    username: 'anonymous'
    password: ''
  cmems:
    type: 'cmems'
    username: !ENV CMEMS_USERNAME
    password: !ENV CMEMS_PASSWORD
  cmems_in_situ:
    type: 'netcdf'
    longitude_attribute: 'LONGITUDE'
    latitude_attribute: 'LATITUDE'
  scihub:
    type: 'copernicus_scihub'
    username: !ENV COPERNICUS_OPEN_HUB_USERNAME
    password: !ENV COPERNICUS_OPEN_HUB_PASSWORD
  creodias:
    type: 'resto'
    url: 'https://datahub.creodias.eu'
  copernicus_data_space:
    type: 'resto'
    url: 'https://catalogue.dataspace.copernicus.eu'
  earthdata_cmr:
    type: 'earthdata_cmr'
  gportal:
    type: 'gportal_ftp'
    username: !ENV JAXA_USERNAME
    password: !ENV JAXA_PASSWORD
  sla_aviso:
    type: 'netcdf'
    longitude_attribute: 'longitude'
    latitude_attribute: 'latitude'
  metno:
    type: 'metno'
  noaa:
    type: 'noaa'
    username: !ENV JAXA_USERNAME
    password: !ENV JAXA_PASSWORD
  podaac:
    type: 'podaac'
  cpom:
    type: 'netcdf'
    longitude_attribute: 'lon'
    latitude_attribute: 'lat'
  nansat:
    type: 'nansat'
  netcdf_l:
    type: 'netcdf'
    longitude_attribute: 'longitude'
    latitude_attribute: 'latitude'
  netcdf_L:
    type: 'netcdf'
    longitude_attribute: 'LONGITUDE'
    latitude_attribute: 'LATITUDE'
  argo_profile:
    type: 'tabledap'
    url: 'https://erddap.ifremer.fr/erddap/tabledap/ArgoFloats.json'
    entry_id_prefix: 'argo_profile_'
    id_attrs: ['platform_number', 'cycle_number']
    longitude_attr: 'longitude'
    latitude_attr: 'latitude'
    time_attr: 'time'
    position_qc_attr: 'position_qc'
    time_qc_attr: 'time_qc'
    valid_qc_codes: ['1', '2', '8']
    variables:
    - 'platform_number'
    - 'cycle_number'
    - 'pres'
    - 'pres_qc'
    - 'pres_adjusted'
    - 'pres_adjusted_qc'
    - 'pres_adjusted_error'
    - 'temp'
    - 'temp_qc'
    - 'temp_adjusted'
    - 'temp_adjusted_qc'
    - 'temp_adjusted_error'
    - 'psal'
    - 'psal_qc'
    - 'psal_adjusted'
    - 'psal_adjusted_qc'
    - 'psal_adjusted_error'
  argo_trajectory:
    type: 'tabledap'
    url: 'https://erddap.ifremer.fr/erddap/tabledap/ArgoFloats.json'
    entry_id_prefix: 'argo_trajectory_'
    id_attrs: ['platform_number']
    longitude_attr: 'longitude'
    latitude_attr: 'latitude'
    time_attr: 'time'
    position_qc_attr: 'position_qc'
    time_qc_attr: 'time_qc'
    valid_qc_codes: ['1', '2', '8']
    variables:
    - 'platform_number'
  bioargo_profile:
    type: 'tabledap'
    url: 'https://erddap.ifremer.fr/erddap/tabledap/ArgoFloats-synthetic-BGC.json'
    entry_id_prefix: 'bioargo_profile_'
    id_attrs: ['platform_number', 'cycle_number']
    longitude_attr: 'longitude'
    latitude_attr: 'latitude'
    time_attr: 'time'
    position_qc_attr: 'position_qc'
    time_qc_attr: 'time_qc'
    valid_qc_codes: ['1', '2', '8']
    variables:
    - 'platform_number'
    - 'cycle_number'
    - 'pres'
    - 'pres_qc'
    - 'pres_adjusted'
    - 'pres_adjusted_qc'
    - 'pres_adjusted_error'
    - 'doxy'
    - 'doxy_qc'
    - 'doxy_adjusted'
    - 'doxy_adjusted_qc'
    - 'chla'
    - 'chla_qc'
    - 'chla_adjusted'
    - 'chla_adjusted_qc'
  bioargo_trajectory:
    type: 'tabledap'
    url: 'https://erddap.ifremer.fr/erddap/tabledap/ArgoFloats-synthetic-BGC.json'
    entry_id_prefix: 'bioargo_trajectory_'
    id_attrs: ['platform_number']
    longitude_attr: 'longitude'
    latitude_attr: 'latitude'
    time_attr: 'time'
    position_qc_attr: 'position_qc'
    time_qc_attr: 'time_qc'
    valid_qc_codes: ['1', '2', '8']
    variables:
    - 'platform_number'
...