---
version: 1
formatters:
  precise:
    format: '%(asctime)s - %(name)s - %(threadName)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: 'logging.StreamHandler'
    formatter: 'precise'
    stream  : 'ext://sys.stdout'
loggers:
  geospaas_harvesting:
    level: 'INFO'
    handlers:
      - 'console'
...
