# Generated by Django 3.2.25 on 2025-06-18 12:24

from django.db import migrations, models
import geospaas_harvesting.providers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('normalizer_name', models.CharField(max_length=100)),
                ('crawler_name', models.CharField(max_length=100)),
                ('config', models.JSONField(validators=[geospaas_harvesting.providers.validate_provider_config])),
            ],
        ),
    ]
