---
name: "Unit tests and docker image build"
on:
  push:
    branches: ['**']
  release:
    types: [prereleased, released]
jobs:
  tests_and_docker_build:
    name: 'Run tests and build docker image'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        python_version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
    env:
      BASE_IMAGE: "${{ vars.DOCKER_ORG }}/geospaas:2.5.2-python${{ matrix.python_version }}"
      IMAGE_NAME: "${{ vars.DOCKER_ORG }}/geospaas_harvesting"
      METANORM_VERSION: '4.2.1'
      GEOSPAAS_DB_HOST: 'db'
      GEOSPAAS_DB_USER: 'test'
      GEOSPAAS_DB_PASSWORD: "${{ secrets.GEOSPAAS_DB_PASSWORD }}"
      latest: ${{ matrix.python_version == '3.11' && 'true' || '' }}
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Create test docker network'
        run: docker network create testing

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build testing image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          target: base
          build-args: |
            BASE_IMAGE=${{ env.BASE_IMAGE }}
            METANORM_VERSION=${{ env.METANORM_VERSION }}
          push: false
          load: true
          tags: 'harvesting_tests'
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: 'Start testing database'
        run: /bin/bash ./scripts/start_test_database.sh

      - name: 'Run tests'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
             docker run --rm
             --network testing
             -v "$(pwd):/src"
             -e "GITHUB_ACTIONS=$GITHUB_ACTIONS"
             -e "GITHUB_REF=$GITHUB_REF"
             -e "GITHUB_SHA=$GITHUB_SHA"
             -e "GITHUB_HEAD_REF=$GITHUB_HEAD_REF"
             -e "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
             -e "GITHUB_RUN_ID=$GITHUB_RUN_ID"
             -e "GITHUB_TOKEN=$GITHUB_TOKEN"
             -e "GEOSPAAS_DB_HOST=${GEOSPAAS_DB_HOST}"
             -e "GEOSPAAS_DB_USER=${GEOSPAAS_DB_USER}"
             -e "GEOSPAAS_DB_PASSWORD=${GEOSPAAS_DB_PASSWORD}"
             'harvesting_tests'
             bash -c "coverage run ./runtests.py && coverage combine"

      - name: 'Stop testing database'
        run: docker stop "${{ env.GEOSPAAS_DB_HOST }}"

      - name: 'Install Python 3.11'
        if: ${{ env.latest }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 'Upload coverage to coveralls.io'
        if: ${{ env.latest }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pip install coveralls && coveralls --service=github

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            BASE_IMAGE=${{ env.BASE_IMAGE }}
            METANORM_VERSION=${{ env.METANORM_VERSION }}
            GEOSPAAS_HARVESTING_RELEASE=${{ github.ref_type == 'tag' && github.ref_name || '0.0.0' }}
          push: ${{ github.event_name == 'release' }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.ref_name }}-python${{ matrix.python_version }}
            ${{ env.latest && format('{0}:{1}', env.IMAGE_NAME, github.ref_name) || '' }}
            ${{ env.IMAGE_NAME }}:latest-python${{ matrix.python_version }}
            ${{ env.latest && format('{0}:latest', env.IMAGE_NAME) || '' }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache


  publish_python_package:
    name: Build Python package and publish it as a release artifact
    runs-on: 'ubuntu-latest'
    needs: 'tests_and_docker_build'
    if: ${{ github.event_name == 'release' }}
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Build Python package'
        run: >
             docker run --rm
             -v "$(pwd):/src"
             -e "GEOSPAAS_HARVESTING_RELEASE=${{ github.ref_name }}"
             "${{ vars.DOCKER_ORG }}/geospaas:latest"
             python setup.py sdist bdist_wheel

      - name: 'Deploy package to the Github release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'dist/*'
          file_glob: true
          tag: ${{ github.ref }}
...